#!/usr/bin/env python
"""Generate the published schema index for the Pages artifact.

The pages job publishes the whole format tree so every `$id` dereferences, but
GitHub Pages serves **no directory listings**: without this page
``https://tylereno.me/oidf/schemas/`` 404s even though every schema resolves.

The index and the machine-readable manifest are derived from the *same* scan as
``tooling/verify_pages_ids.py`` (imported, not re-implemented), so the published
listing cannot drift from the enforced identifier namespace.

Usage::

    python tooling/gen_schema_index.py --out public/schemas/index.html
"""

from __future__ import annotations

import argparse
import html
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from verify_pages_ids import BASE, DEFAULT_ROOT, STAGED_SUFFIXES, load_id, served_rel  # noqa: E402

PAGE_CSS = """
:root { color-scheme: dark; }
body { margin: 0 auto; max-width: 62rem; padding: 3rem 1.25rem; background: #101418;
       color: #e6ebf1; font: 15px/1.6 ui-monospace, SFMono-Regular, Menlo, Consolas, monospace; }
h1 { font-size: 1.5rem; margin: 0 0 .25rem; }
p.sub { margin: 0 0 2rem; color: #93a1b1; }
code, a { font: inherit; }
a { color: #7cc4ff; text-decoration: none; }
a:hover { text-decoration: underline; }
h2 { font-size: 1rem; margin: 2rem 0 .5rem; color: #b9c6d4; border-bottom: 1px solid #24303c;
     padding-bottom: .35rem; }
ul { list-style: none; margin: 0; padding: 0; }
li { padding: .3rem 0; border-bottom: 1px dashed #1c2530; word-break: break-all; }
li:last-child { border-bottom: 0; }
span.src { display: block; color: #7d8b9a; font-size: .82rem; }
footer { margin-top: 3rem; color: #7d8b9a; font-size: .82rem; }
"""


def collect(root: Path, base: str) -> list[dict]:
    """Return one record per file that declares an `$id`, sorted by served path."""
    records = []
    for path in sorted(root.rglob("*")):
        if not path.is_file() or path.suffix.lower() not in STAGED_SUFFIXES:
            continue
        if path.name == "README.md":
            continue
        schema_id = load_id(path)
        if not schema_id:
            continue
        rel = served_rel(path, root)
        records.append({
            "served_path": rel,
            "url": base + rel[len("schemas/"):],
            "source_path": str(path).replace("\\", "/"),
        })
    records.sort(key=lambda r: r["served_path"])
    return records


def render(records: list[dict], base: str) -> str:
    groups: dict[str, list[dict]] = {}
    for record in records:
        groups.setdefault(record["served_path"].rsplit("/", 1)[0] or "schemas", []).append(record)

    out = [
        "<!DOCTYPE html>",
        '<html lang="en"><head><meta charset="utf-8">',
        '<meta name="viewport" content="width=device-width, initial-scale=1">',
        "<title>OIDF published schema index</title>",
        f"<style>{PAGE_CSS}</style>",
        "</head><body>",
        "<h1>OIDF published schema index</h1>",
        f'<p class="sub">{len(records)} <code>$id</code>-declaring files under '
        f"<code>{html.escape(base)}</code></p>",
    ]
    for group in sorted(groups):
        out.append(f"<h2>{html.escape(group)}/</h2>")
        out.append("<ul>")
        for record in groups[group]:
            name = record["served_path"].rsplit("/", 1)[-1]
            out.append(
                "<li>"
                f'<a href="{html.escape(record["url"])}">{html.escape(name)}</a>'
                f'<span class="src">$id {html.escape(record["url"])}'
                f' &middot; source {html.escape(record["source_path"])}</span>'
                "</li>"
            )
        out.append("</ul>")
    out += [
        "<footer>Generated by <code>tooling/gen_schema_index.py</code> during the Pages "
        "build &mdash; do not edit by hand. Same scan as "
        "<code>tooling/verify_pages_ids.py</code>, which fails the build if any "
        "<code>$id</code> is not served at its published path. "
        "OIDF is a format surface; the runtime implementation is separate.</footer>",
        "</body></html>",
        "",
    ]
    return "\n".join(out)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", default=str(DEFAULT_ROOT))
    parser.add_argument("--out", required=True, help="index HTML path inside the artifact")
    parser.add_argument("--base", default=BASE)
    args = parser.parse_args()

    root = Path(args.root)
    if not root.is_dir():
        print(f"FAIL  schema root not found: {root}")
        return 2

    records = collect(root, args.base)
    if not records:
        print(f"FAIL  no $id-declaring files under {root}")
        return 1

    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(render(records, args.base), encoding="utf-8")

    manifest = out.parent / "manifest.json"
    manifest.write_text(
        json.dumps({"authority": args.base, "count": len(records), "schemas": records},
                   indent=2) + "\n",
        encoding="utf-8",
    )

    print(f"index    : {out} ({out.stat().st_size} bytes)")
    print(f"manifest : {manifest} ({manifest.stat().st_size} bytes)")
    print(f"schemas  : {len(records)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
